# Generated by Django 5.0.3 on 2024-03-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_department_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('sales', 'Sales'), ('engineering', 'Engineering'), ('hr', 'Human Resources')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('manager', 'Manager'), ('assistant', 'Assistant'), ('developer', 'Developer'), ('hr_specialist', 'HR Specialist')], max_length=100),
        ),
    ]
